# ============================================================
# CITY CONFIGURATIONS - EXPANDED
# Replace the existing CITIES dict (lines 79-108) with this
# ============================================================

CITIES = {
    "NYC": {
        "name": "New York City",
        "nws_station": "KNYC",
        "nws_gridpoint": "OKX/33,37",
        "kalshi_high": "KXHIGHNY",
        "kalshi_low": "KXLOWNY",
        "lat": 40.7128,
        "lon": -74.0060,
    },
    "CHI": {
        "name": "Chicago",
        "nws_station": "KORD",
        "nws_gridpoint": "LOT/76,73",
        "kalshi_high": "KXHIGHCHI",
        "kalshi_low": "KXLOWCHI",
        "lat": 41.8781,
        "lon": -87.6298,
    },
    "MIA": {
        "name": "Miami",
        "nws_station": "KMIA",
        "nws_gridpoint": "MFL/109,50",
        "kalshi_high": "KXHIGHMIA",
        "kalshi_low": "KXLOWMIA",
        "lat": 25.7617,
        "lon": -80.1918,
    },
    "DEN": {
        "name": "Denver",
        "nws_station": "KDEN",
        "nws_gridpoint": "BOU/62,60",
        "kalshi_high": "KXHIGHDEN",
        "kalshi_low": "KXLOWDEN",
        "lat": 39.7392,
        "lon": -104.9903,
    },
    "LAX": {
        "name": "Los Angeles",
        "nws_station": "KLAX",
        "nws_gridpoint": "LOX/154,44",
        "kalshi_high": "KXHIGHLA",
        "kalshi_low": "KXLOWLA",
        "lat": 34.0522,
        "lon": -118.2437,
    },
    "PHX": {
        "name": "Phoenix",
        "nws_station": "KPHX",
        "nws_gridpoint": "PSR/159,59",
        "kalshi_high": "KXHIGHPHX",
        "kalshi_low": "KXLOWPHX",
        "lat": 33.4484,
        "lon": -112.0740,
    },
    "DFW": {
        "name": "Dallas",
        "nws_station": "KDFW",
        "nws_gridpoint": "FWD/80,108",
        "kalshi_high": "KXHIGHDFW",
        "kalshi_low": "KXLOWDFW",
        "lat": 32.7767,
        "lon": -96.7970,
    },
    "HOU": {
        "name": "Houston",
        "nws_station": "KIAH",
        "nws_gridpoint": "HGX/65,97",
        "kalshi_high": "KXHIGHHOU",
        "kalshi_low": "KXLOWHOU",
        "lat": 29.7604,
        "lon": -95.3698,
    },
    "ATL": {
        "name": "Atlanta",
        "nws_station": "KATL",
        "nws_gridpoint": "FFC/51,88",
        "kalshi_high": "KXHIGHATL",
        "kalshi_low": "KXLOWATL",
        "lat": 33.7490,
        "lon": -84.3880,
    },
    "BOS": {
        "name": "Boston",
        "nws_station": "KBOS",
        "nws_gridpoint": "BOX/71,90",
        "kalshi_high": "KXHIGHBOS",
        "kalshi_low": "KXLOWBOS",
        "lat": 42.3601,
        "lon": -71.0589,
    },
    "SEA": {
        "name": "Seattle",
        "nws_station": "KSEA",
        "nws_gridpoint": "SEW/124,67",
        "kalshi_high": "KXHIGHSEA",
        "kalshi_low": "KXLOWSEA",
        "lat": 47.6062,
        "lon": -122.3321,
    },
    "LAS": {
        "name": "Las Vegas",
        "nws_station": "KLAS",
        "nws_gridpoint": "VEF/126,97",
        "kalshi_high": "KXHIGHLAS",
        "kalshi_low": "KXLOWLAS",
        "lat": 36.1699,
        "lon": -115.1398,
    },
    "MSP": {
        "name": "Minneapolis",
        "nws_station": "KMSP",
        "nws_gridpoint": "MPX/107,71",
        "kalshi_high": "KXHIGHMSP",
        "kalshi_low": "KXLOWMSP",
        "lat": 44.9778,
        "lon": -93.2650,
    },
    "DET": {
        "name": "Detroit",
        "nws_station": "KDTW",
        "nws_gridpoint": "DTX/65,33",
        "kalshi_high": "KXHIGHDET",
        "kalshi_low": "KXLOWDET",
        "lat": 42.3314,
        "lon": -83.0458,
    },
    "PHL": {
        "name": "Philadelphia",
        "nws_station": "KPHL",
        "nws_gridpoint": "PHI/57,97",
        "kalshi_high": "KXHIGHPHL",
        "kalshi_low": "KXLOWPHL",
        "lat": 39.9526,
        "lon": -75.1652,
    },
    "SFO": {
        "name": "San Francisco",
        "nws_station": "KSFO",
        "nws_gridpoint": "MTR/84,105",
        "kalshi_high": "KXHIGHSF",
        "kalshi_low": "KXLOWSF",
        "lat": 37.7749,
        "lon": -122.4194,
    },
    "DCA": {
        "name": "Washington DC",
        "nws_station": "KDCA",
        "nws_gridpoint": "LWX/96,70",
        "kalshi_high": "KXHIGHDC",
        "kalshi_low": "KXLOWDC",
        "lat": 38.9072,
        "lon": -77.0369,
    },
}
